# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Kiddinglife's Blog
url: http://Kiddinglife.github.io/
feed: /atom.xml
author_info: <a href="http://Kiddinglife.github.io/">Kiddinglife</a>

myblog:
  gavatar: images/2.jpg
  gpname: Kiddinglife
  linkedin: http://www.linkedin.com/in/taotaoli
  github: https://github.com/Kiddinglife
  email: mailto:jakezhang1989@hotmail.com
  coverimgs: []
  postbgimg: []

categories: [web, tools, spark, new-spark, python, money, erlang, db, books]
